# Site settings
title: lfkeitel (Lee Keitel)
email: keitellf@gmail.com
description: "Official blog of lfkeitel (Lee Keitel)."
baseurl: ""
url: "http://lfkeitel.github.io"
github_username:  lfkeitel

# Build settings
markdown: kramdown
