# Site settings
title: Onesimus Systems
email: onesimussystems@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Official blog and news source for Onesimus Systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://onesimussystems.com" # the base hostname & protocol for your site
github_username:  dragonrider23

# Build settings
markdown: kramdown
