# Site settings
title: dragonrider23 (Lee Keitel)
email: keitellf@gmail.com
description: "Official blog of dragonrider23 (Lee Keitel)."
baseurl: ""
url: "http://dragonrider23.github.io"
github_username:  dragonrider23

# Build settings
markdown: kramdown
